languageCode = 'en-us'
title = 'HamWAN Memphis Metro Wiki'
theme = 'hugo-geekdoc'
baseURL = "https://wiki.memhamwan.org"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

[params]
  geekdocRepo = "https://github.com/memhamwan/wiki"
  geekdocEditPath = "edit/main"
  geekdocCollapseAllSections = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"
